### ISSUE TITLE
Fix the sound issues

### ISSUE THREAD

**Issue by loganwyas** [oss-slu/Mouser#158]
Currently, there are a few problems with how sound is played within the application, mostly in regards to errors that pop up at random. Playsound is not working properly, so maybe look at the [Speech Transcription application](https://github.com/oss-slu/SpeechTranscription) for help.

What is required for this issue to be completed:
- [x] Find a new library that works better for the application
- [x] Add the new library to the requirements.txt
- [x] Additional audio implementation
  - [x] Modify both map_rfid.py and data_collection_ui.py to play a "success" sound when data is successfully entered
  - [x] Modify any files that have warning/error dialogs to play an "error" sound when those dialogs are opened

**Comment by aobermiller** [comment]
Speech Transcription uses Pyaudio
