### ISSUE TITLE
Implement serial port controller in data collection

### ISSUE THREAD

**Issue by stanleyyang2001** [oss-slu/Mouser#207]
**Describe the feature that you would like added**
Data collection requires serial port connection to the data collecting device. However, the serial port controller for data collection isn't implemented yet for data collection, which needs to be implemented

**Tasks that need to complete for this feature**
Implement the serial port controller in the data collection module, and connect the controller to the serial port setting.

**Additional context**
You can refer to map RFID module to see how serial port controller is implemented there. For how to connect the serial port setting to controller, you can either create another controller or find a way to use one controller for two different places of the application.

**Comment by jackbelyeu** [comment]
Issue is resolved
